<a href="https://colab.research.google.com/github/knikhilbharath/Pytorch/blob/main/2_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from pytorch import torch
w = torch.tensor(2.0, requires_grad = True)
b = torch.tensor(3.0, requires_grad = True)

ModuleNotFoundError: No module named 'pytorch'

In [ ]:
def forward(x):
  y = w*x + b
  return y

In [ ]:
x = torch.tensor([[2.0], [3.3]])
forward(x)

tensor([[7.0000],
        [9.6000]], grad_fn=<AddBackward0>)

**Linear Class**

In [ ]:
import torch
from torch.nn import Linear

In [ ]:
torch.manual_seed(1)
model = Linear(in_features=1, out_features=1)
print(model.bias, model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [ ]:
x = torch.tensor([[4], [6.7]])
print(model(x))
print(x)

NameError: name 'torch' is not defined

**Custom modules**

In [ ]:
import torch
import torch.nn as nn

In [ ]:
class LR(nn.Module):
  def __init__(self, input_size, output_size):
    super().__init__()
    self.linear = nn.Linear(input_size, output_size)

  def forward(self, x):
    pred = self.linear(x)
    return pred

In [ ]:
torch.manual_seed(1)
model = LR(1, 1)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [ ]:
x = torch.tensor([[4.0], [5.5]])
print(model.forward(x))

tensor([[1.6197],
        [2.3926]], grad_fn=<AddmmBackward0>)
