<a href="https://colab.research.google.com/github/knikhilbharath/Pytorch/blob/Pytorch_Official/Linear%20regresson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Making Predictions**

In [1]:
import torch
w = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

In [2]:
def forward(x):
  y = w*x + b
  return y

In [3]:
x = torch.tensor(2.0)
forward(x)

tensor(7., grad_fn=<AddBackward0>)

In [4]:
x = torch.tensor([[3.0], [6.0]])
forward(x)

tensor([[10.],
        [19.]], grad_fn=<AddBackward0>)

**Linear Class**

In [5]:
import torch
from torch.nn import Linear
torch.manual_seed(1)
model = Linear(in_features=1, out_features=1)
print(model.bias, model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [ ]:
x = torch.tensor([[2.0], [4.0]])
print(model(x))